kind: ExecutorPlugin
apiVersion: argoproj.io/v1alpha1
metadata:
  name: mongodb
  annotations:
    workflows.argoproj.io/description: |
      This is the "mongodb" plugin.

      Example:

      ```yaml
      apiVersion: argoproj.io/v1alpha1
      kind: Workflow
      metadata:
        generateName: mongodb-example-
      spec:
        entrypoint: main
        templates:
          - name: main
            plugin:
              mongodb: {
                connectionURI: "mongodb://mongodb:27017",
                database: "mydb",
                collection: "mycollection",
                operation: "insertOne",
                document: {
                  "hello": "world"
                }
              }
      ```
    workflows.argoproj.io/version: '>= v3.3'
spec:
  sidecar:
    container:
      image: mongodb-plugin:latest
      name: mongodb-plugin
      ports:
        - containerPort: 30005
      resources:
        requests:
          cpu: 100m
          memory: 32Mi
        limits:
          cpu: 200m
          memory: 64Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL